INSERT INTO events (id, name) VALUES (1, ‘CREATED’);
INSERT INTO events (id, name) VALUES (2, ‘REGISTERED FOR MODULE’);
INSERT INTO events (id, name) VALUES (3, ‘PRINCIPAL VERIFIED’);
INSERT INTO events (id, name) VALUES (4, ‘SIGN IN SUCCEEDED’);
INSERT INTO events (id, name) VALUES (5, ‘SIGN IN FAILED’);
INSERT INTO events (id, name) VALUES (6, ‘SIGNED OUT’);
INSERT INTO events (id, name) VALUES (7, ‘FORGOT CREDENTIAL’);
INSERT INTO events (id, name) VALUES (8, ‘CREDENTIAL CHANGED’);
INSERT INTO events (id, name) VALUES (9, ‘FIRSTNAME CHANGED’);
INSERT INTO events (id, name) VALUES (10, ‘LASTNAME CHANGED’);
INSERT INTO events (id, name) VALUES (11, ‘DESCRIPTION CHANGED’);
INSERT INTO events (id, name) VALUES (12, ‘UNREGISTERED FROM MODULE’);
INSERT INTO events (id, name) VALUES (13, ‘SUSPENDED’);

